### ISSUE TITLE
Some question about Table 1 and Table 2

### ISSUE THREAD

**Issue by wsy-yjys** [xinghaochen/DECO#1]
Your work is excellent, but there are two questions about the paper：

- Question 1. Are all the comparison algorithms in Table 1 only half-trained epochs,  such as 150 epochs for fair comparison?

- Question 2. Are all the comparison algorithms in Table 2 only train 150 epochs?

**Comment by xinghaochen** [comment]
As we stated in the experimental settings, we train our models as well as the reported DETR and RT-DETR for 150 epochs. APs of other detectors are directly cited from the original papers or github repos.
