### ISSUE TITLE
Is there a script to test fps？

### ISSUE THREAD

**Issue by wsy-yjys** [xinghaochen/DECO#2]

**Comment by xinghaochen** [comment]
We simply follow DETR to measure FPS over the first 100 val5k COCO images, you can refer to this [issue](https://github.com/facebookresearch/detr/issues/110)  for [scripts](https://gist.github.com/fmassa/c0fbb9fe7bf53b533b5cc241f5c8234c) and more details.

**Comment by wsy-yjys** [comment]
Okay, thank you.
