### ISSUE TITLE
About DecoderLayer

### ISSUE THREAD

**Issue by Yyc1999super** [xinghaochen/DECO#4]
Excuse me，how Decoder handles multi-scale features that we get from the CCFM(RT-DETR) of Encoder?

**Comment by yijingyang710** [comment]
After CCFM, the multi-scale features are mapped to the same resolution. Then, they are concatenated along the channels followed by a linear projection layer to project to `hidden_dim`.  This part is special in DECO+ and we will release the code soon. 

Hope this helps.

**Comment by Yyc1999super** [comment]
Okay, thank you.

**Comment by ssli23** [comment]
> After CCFM, the multi-scale features are mapped to the same resolution. Then, they are concatenated along the channels followed by a linear projection layer to project to `hidden_dim`. This part is special in DECO+ and we will release the code soon.
> 
> Hope this helps.

Hello, sorry to bother you. Has the DECO+ version not been released yet?

**Comment by xinghaochen** [comment]
> > After CCFM, the multi-scale features are mapped to the same resolution. Then, they are concatenated along the channels followed by a linear projection layer to project to `hidden_dim`. This part is special in DECO+ and we will release the code soon.
> > Hope this helps.
> 
> Hello, sorry to bother you. Has the DECO+ version not been released yet?

We have just released the related codes.
